### PR TITLE
Switch to native asserts

### PR DESCRIPTION
**Pull request by davehunt**
@bobsilverberg r?

### CODE REVIEW

**Comment by davehunt** [comment]
Adhoc: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/moztrap.adhoc/39/

**Comment by bobsilverberg** [comment]
LGTM, r+, although it looks like it now needs to be rebased.

**Comment by bobsilverberg** [comment]
Actually, I can just do that myself. :)

**Comment by bobsilverberg** [comment]
Hmm, it won't let me do it because the branch is protected and it doesn't recognize the commit as being tested. I need to close this PR and open a new one for the rebase.

**Comment by davehunt** [comment]
Thanks @bobsilverberg!

**Pull request closed without merging**
