### PR TITLE
Add a setup.cfg file to configure the behaviour of flake8

### PR DESCRIPTION
**Pull request by IamAdiSri**
moztrap-tests
issue #164

### CODE REVIEW

**Comment by rbillings** [comment]
R+

**Comment by bobsilverberg** [comment]
Great work, @IamAdiSri! Please see my comment about squashing commits at https://github.com/mozilla/sumo-tests/pull/307#issuecomment-101787890. 

Either try to squash the commits yourself, or let us know if you'd rather have us do it for you.

**Comment by IamAdiSri** [comment]
@bobsilverberg Is this it?

**Comment by bobsilverberg** [comment]
@IamAdiSri Yes, that looks perfect! Thank you for your efforts and perseverance! Great work!

**Comment by IamAdiSri** [comment]
@bobsilverberg Thank you for your assistance. Am i eligible for a badge now?

**Comment by stephendonner** [comment]
@IamAdiSri you most certainly are: please log in with your Persona account at https://badges.mozilla.org/en-US/badges/badge/WebQA-1-pull-request-merged and follow the instructions!  Thanks and congrats!

**Pull request merged**
