### PR TITLE
Migrate to pytest-selenium and update README

### PR DESCRIPTION
**Pull request by davehunt**
@stephendonner r? (please feel free to bounce the review request to someone else)

### CODE REVIEW

**Comment by davehunt** [comment]
Passing adhoc: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/moztrap.adhoc.pytest-selenium/1/

**Comment by stephendonner** [comment]
Thanks, Dave!  Also, so proud of myself - got this running locally (passed!) and took the time to review the README as well as the code changes:

(moztrap-tests) sdonners-MBP:moztrap-tests sdonner$ py.test --driver=Firefox --variables moztrap.json
============================= test session starts ==============================
platform darwin -- Python 2.7.11 -- py-1.4.31 -- pytest-2.7.3
rootdir: /Users/sdonner/moztrap-tests, inifile: setup.cfg
plugins: html, selenium, selenium, selenium, selenium, selenium, selenium, selenium, selenium, selenium, selenium, variables
collected 36 items 

tests/test_homepage.py ....
tests/test_manage_cases_page.py ....
tests/test_manage_products_page.py ...
tests/test_manage_profiles_page.py .
tests/test_manage_runs_page.py ..
tests/test_manage_suites_page.py ....
tests/test_manage_tags_page.py ...
tests/test_manage_versions_page.py ...
tests/test_pinning_filters.py ...X..
tests/test_run_tests_page.py ......

=================== 35 passed, 1 xpassed in 1525.78 seconds ====================

r+

**Comment by stephendonner** [comment]
Throwing the r? love around to @mozilla/web-qa-sorcerers as well!

**Comment by m8ttyB** [comment]
r+ 
bitdance

**Comment by davehunt** [comment]
Eek. I should have mentioned that this should not be merged until Jenkins has been updated.

**Comment by davehunt** [comment]
If I get time I'll update Jenkins today.

**Comment by davehunt** [comment]
Awesome - @stephendonner  already took care of it! :smile: I just updated the dev jobs (even though they're disabled) and made a couple of additional tweaks. Thanks!

**Pull request merged**
